# Configuração do RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# Fila de transações
app.rabbitmq.queue=${TRANSACTION_QUEUE:transactions.queue}

# Porta do servidor
server.port=8081

# Exposição dos endpoints de gerenciamento
management.endpoints.web.exposure.include=*

# OTLP (OpenTelemetry) - métricas
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4318/v1/metrics}
