version: '3.8'

x-rabbit-env: &rabbit_env
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: 5672
  SPRING_RABBITMQ_USERNAME: test
  SPRING_RABBITMQ_PASSWORD: test

x-spring-common: &spring_common
  depends_on:
    rabbitmq:
      condition: service_healthy
  networks:
    - wallet-network-dev
  restart: unless-stopped

services:
  wallet-service:
    build:
      context: .
      dockerfile: wallet-service/Dockerfile
    image: wallet-service:latest
    container_name: wallet-service-dev
    ports:
      - "8080:8080"
    environment:
      <<: *rabbit_env
      SPRING_PROFILES_ACTIVE: dev
    <<: *spring_common

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    image: notification-service:latest
    container_name: notification-service-dev
    ports:
      - "8081:8081"
    environment:
      <<: *rabbit_env
      MANAGEMENT_OTLP_METRICS_EXPORT_ENABLED: "false"
    <<: *spring_common

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    image: payment-service:latest
    container_name: payment-service-dev
    ports:
      - "8082:8082"
    environment:
      <<: *rabbit_env
      SPRING_PROFILES_ACTIVE: dev
    <<: *spring_common

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: user-service:latest
    container_name: user-service-dev
    ports:
      - "8083:8083"
    environment:
      <<: *rabbit_env
      SPRING_PROFILES_ACTIVE: dev
    <<: *spring_common


  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - wallet-network-dev
    restart: unless-stopped

networks:
  wallet-network-dev:
    driver: bridge