version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wallet-service:latest
    container_name: wallet-service-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - wallet-network-dev
    restart: unless-stopped

  notification:
    build:
      context: ./notificarion-service
      dockerfile: Dockerfile
    image: notificarion-service:latest
    container_name: notificarion-service-dev
    depends_on:
      - rabbitmq
    networks:
      - wallet-network-dev
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-dev
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - wallet-network-dev
    restart: unless-stopped

networks:
  wallet-network-dev:
    driver: bridge

