version: '3.8'

services:
  wallet-service:
    build:
      context: ./wallet-service
      dockerfile: Dockerfile
    image: wallet-service:latest
    container_name: wallet-service-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq
    networks:
      - wallet-network-dev
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    networks:
      - wallet-network-dev
    restart: unless-stopped

networks:
  wallet-network-dev:
    driver: bridge