# Server
server.port=8080

# Default Profile
spring.profiles.active=dev

# JPA/Hibernate
spring.jpa.show-sql=true

# Logging
logging.level.org.springframework=INFO
logging.level.com.wallet.service=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
