# Server
server.port=8080

# Default Profile
spring.profiles.active=dev

# JPA/Hibernate
spring.jpa.show-sql=true

# Logging
logging.level.org.springframework=INFO
logging.level.com.wallet.service=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Actuator and Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# Tracing
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
