# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/walletdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate


# Logging
logging.level.org.springframework=INFO
logging.level.com.wallet.service=INFO
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR

# Spring Doc
springdoc.api-docs.enabled=false