version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wallet-service:latest
    container_name: wallet-service-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - wallet-network-dev
    restart: unless-stopped

networks:
  wallet-network-dev:
    driver: bridge

