# Server
server.port=8083

# Default Profile
spring.profiles.active=dev

spring.application.name=user-service

# JPA/Hibernate
spring.jpa.show-sql=true

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:test}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:test}

management.endpoints.web.exposure.include=health,info,prometheus
management.otlp.metrics.export.enabled=true
management.tracing.enabled=true
logging.level.root=INFO